### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by SupremeSports**
Instead of hardcoding values, user can change them in definition/setup

The extra features of this request:
1. setSyncDir(uint8_t dir) to adjust the interrupt direction FALLING, RISING, CHANGE
2. setSyncPullup(bool pullup) to activate internal pull-up resistor on zero-crossing detection
3. setGateTurnOffTime(uint16_t timeOff) to change the value of the gate turn off time

### CODE REVIEW

**Comment by bcelary** [comment]
I am wondering why this couldn't be accepted. Are there any issues with a different edge direction of the interrupt or having an internal pull up resistor enabled? I am using some optocoupler that forces me to either mess with soldering pull down resistor or simply change to FALLING and enable pull up resistor to make it easier. Wondering if I could simply use this patch :thinking:

**Comment by SupremeSports** [comment]
> I am wondering why this couldn't be accepted. Are there any issues with a different edge direction of the interrupt or having an internal pull up resistor enabled? I am using some optocoupler that forces me to either mess with soldering pull down resistor or simply change to FALLING and enable pull up resistor to make it easier. Wondering if I could simply use this patch :thinking: 

I had the same optocoupler issue, that's why I did this update and gave it to them but they won't accept it 

It works flawlessly on my project

**Comment by bcelary** [comment]
Thanks. I have already forked the repo to change the maximum dimmers, so might as well use this pull request. I am using Arduino Mega. Will see how it goes.

**Comment by fabianoriccardi** [comment]
Sorry, I missed this update. I gave it a quick glance and it seems fine. I will review it as soon as possible!

**Pull request merged**
