### PR TITLE
Add Pico RP2040 (non-mbed) support

### PR DESCRIPTION
**Pull request by adisbladis**
This adds support for RP2040 based boards such as the Pico and the Pico W using arduino-pico.
Note that this is distinctly different from the mbed-OS based platform which would have to be implemented separately.

I have tested this on a Pico W.

Github Actions related changes haven't been tested, only actually running the code on my board.

### CODE REVIEW

**Comment by adisbladis** [comment]
Ping @fabianoriccardi

**Comment by fabianoriccardi** [comment]
I will test it the next week with the Pico, however I see that some examples don't compile!

**Comment by adisbladis** [comment]
It's very hard to test CI locally because the Github Actions yml files don't exactly correspond to a set of commands that I can run.
The examples compile just fine, it's just hard to figure out the exact set of platform/url/board strings appease the CI.

**Comment by fabianoriccardi** [comment]
Did you tested RPI Pico with PlatformIO?

**Comment by adisbladis** [comment]
> Did you tested RPI Pico with PlatformIO?

Yes. My primary use case for this is my [espresso machine](https://github.com/adisbladis/espressos) where I use platformio to build.

**Comment by fabianoriccardi** [comment]
The same issue appears with your project. [Here](https://github.com/maxgerhardt/platform-raspberrypi/issues/47) I have opened the issue.

**Comment by fabianoriccardi** [comment]
May I add your name in license of hw_timer_pico.cpp/h files?

**Comment by adisbladis** [comment]
> May I add your name in license of hw_timer_pico.cpp/h files?

Feel free.

**Comment by fabianoriccardi** [comment]
Ok 😅 real name or nickname?

**Comment by fabianoriccardi** [comment]
I prefer to insert a real name but you don't use it on GitHub...

**Comment by adisbladis** [comment]
My real name is Adam Hoese.

**Pull request merged**
